version: '3.8'

services:
  mobvue:
    image: node:20.19.4-alpine
    container_name: mobvue_dev
    working_dir: /app
    volumes:
      - .:/app
      # - mobvue_node_modules:/app/node_modules
      - mobvue_pnpm_store:/root/.pnpm-store    # ⬅ thêm dòng này
    ports:
      - "3333:3333"
    command: sh -c "npm install -g pnpm && pnpm config set store-dir ~/.pnpm-store && pnpm install && pnpm run dev"
    environment:
      - HOST=0.0.0.0

volumes:
  mobvue_pnpm_store: 