version: '3.8'

services:
  mobvue:
    image: node:20.19.4-alpine
    container_name: mobvue_dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3333:3333"
    command: sh -c "npm install -g pnpm && pnpm install && pnpm run dev"
    environment:
      - HOST=0.0.0.0
